[features]
seeds = false
skip-lint = false
[programs.devnet]
wall_program = "Ehpw3rFuzgW6w9uwyxZMtwCb9q8xvXyhcj8WuzZh6tz1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/dfeliz/.config/solana/id.json"

[scripts]
test = "node tests/wall_program.js"
